language: cpp

compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjsoncpp-dev libgdcm2-dev libinsighttoolkit3-dev

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - cmake --build .
  - ctest -V .
