language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:jamie-snape/tubetk
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjsoncpp-dev libinsighttoolkit-dev

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - cmake --build .
  - ctest -V .
